sonar.organization=inv-muhammedmirzapn
sonar.projectKey=inv-muhammedmirzapn_flight-reservation-system

sonar.projectName=Flight Reservation System
sonar.projectVersion=1.0

# Source directories
sonar.sources=backend,frontend-v2/src

# Exclusions - files SonarQube should NOT scan
sonar.exclusions=\
  **/venv/**,\
  **/__pycache__/**,\
  **/migrations/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/*.pyc,\
  **/coverage/**,\
  **/media/**,\
  frontend-v2/fix.py,\
  frontend-v2/parse_lint.cjs

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage report paths
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend-v2/coverage/lcov.info

